CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_EVENT
	FOR GATEWAY_OWNR.FSM_EVENT
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_STATE
	FOR GATEWAY_OWNR.FSM_STATE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_STATE_VALUE
	FOR GATEWAY_OWNR.FSM_STATE_VALUE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_TRANSITION_LIST
	FOR GATEWAY_OWNR.FSM_TRANSITION_LIST
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_TRANSITION_STATE
	FOR GATEWAY_OWNR.FSM_TRANSITION_STATE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.PROCESSOR_EXEC_STATE
	FOR GATEWAY_OWNR.PROCESSOR_EXEC_STATE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.STAGED_FILE
	FOR GATEWAY_OWNR.STAGED_FILE
;

