----------------------------------------------------------------
-- UPLOADED_FILE
----------------------------------------------------------------

CREATE TABLE GATEWAY_OWNR.UPLOADED_FILE
(
  PGUID VARCHAR2(36 BYTE) CONSTRAINT NN01_UPLOADED_FILE NOT NULL,
  USERID VARCHAR2(128 BYTE),
  FILE_NAME VARCHAR2(512 BYTE),
  FILE_SIZE VARCHAR2(256 BYTE),
  UPLOADED_COMMENT VARCHAR2(512 BYTE),
  PROFILE_NAME VARCHAR2(512 BYTE) CONSTRAINT NN02_UPLOADED_FILE NOT NULL,
  STATUS VARCHAR2(16),
  UPLOAD_DATE TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN03_UPLOADED_FILE NOT NULL,
  EXPIRY_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP CONSTRAINT NN04_UPLOADED_FILE NOT NULL
)
TABLESPACE GATEWAY_TRNX
STORAGE
(
	PCTINCREASE 0
)
NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.UPLOADED_FILE ADD
    CONSTRAINT PK_UPLOADED_FILE PRIMARY KEY (PGUID)
        USING INDEX
            TABLESPACE GATEWAY_TRNX
            STORAGE
            (
                PCTINCREASE 0
            )
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.UPLOADED_FILE
    FOR GATEWAY_OWNR.UPLOADED_FILE
;

GRANT INSERT ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;
GRANT SELECT ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;
GRANT UPDATE ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;
GRANT DELETE ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;

/**
 * INDEX for mostly used non unique columns
 */
DECLARE
  i INTEGER;
BEGIN
  SELECT COUNT(*)
  INTO i
  FROM user_indexes
  WHERE index_name = 'IX01_UPLOADED_FILE' AND table_owner = 'GATEWAY_OWNR' AND table_name = 'UPLOADED_FILE';
  IF i = 0
  THEN
    EXECUTE IMMEDIATE 'CREATE INDEX GATEWAY_OWNR.UPLOADED_FILE ON GATEWAY_OWNR.UPLOADED_FILE
              (
                FILE_NAME
              )
                LOGGING
                TABLESPACE GATEWAY_TRNX
                PCTFREE    10
                INITRANS   2
                MAXTRANS   255
                STORAGE    (
                          INITIAL          64K
                          NEXT             1M
                          MAXSIZE          UNLIMITED
                          MINEXTENTS       1
                          MAXEXTENTS       UNLIMITED
                          PCTINCREASE      0
                          BUFFER_POOL      DEFAULT
                          FLASH_CACHE      DEFAULT
                          CELL_FLASH_CACHE DEFAULT
                         )
              NOPARALLEL';
  END IF;
END;
/
