----------------------------------------------------------------
-- UPLOADED_FILE
----------------------------------------------------------------

CREATE TABLE GATEWAY_OWNR.UPLOADED_FILE
(
  PGUID VARCHAR2(36 BYTE) CONSTRAINT NN01_UPLOADED_FILE NOT NULL,
  USERID VARCHAR2(128 BYTE),
  FILE_NAME VARCHAR2(512 BYTE),
  FILE_SIZE VARCHAR2(256 BYTE),
  UPLOADED_COMMENT VARCHAR2(512 BYTE),
  PROFILE_NAME VARCHAR2(512 BYTE) CONSTRAINT NN02_UPLOADED_FILE NOT NULL,
  STATUS VARCHAR2(16),
  UPLOAD_DATE TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN03_UPLOADED_FILE NOT NULL,
  EXPIRY_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE GATEWAY_TRNX
STORAGE
(
	PCTINCREASE 0
)
NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.UPLOADED_FILE ADD 
    CONSTRAINT PK_UPLOADED_FILE PRIMARY KEY (PGUID)
        USING INDEX
            TABLESPACE GATEWAY_TRNX
            STORAGE
            (
                PCTINCREASE 0
            )
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.UPLOADED_FILE
    FOR GATEWAY_OWNR.UPLOADED_FILE
;

GRANT INSERT ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;
GRANT SELECT ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;
GRANT UPDATE ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;
GRANT DELETE ON GATEWAY_OWNR.UPLOADED_FILE TO GATEWAY_APPL_ROLE;
