--
-- Copyright 2018 Liaison Technologies, Inc.
-- This software is the confidential and proprietary information of
-- Liaison Technologies, Inc. ("Confidential Information").  You shall
-- not disclose such Confidential Information and shall use it only in
-- accordance with the terms of the license agreement you entered into
-- with Liaison Technologies.
--

----------------------------------------------------------------
-- INBOUND_FILE
----------------------------------------------------------------

DECLARE table_count NUMBER;
BEGIN
  SELECT count(*) INTO table_count FROM all_tables WHERE table_name = 'INBOUND_FILE' AND owner = 'GATEWAY_OWNR';
  IF table_count = 0 THEN 
    EXECUTE IMMEDIATE 'CREATE TABLE GATEWAY_OWNR.INBOUND_FILE
        (
          PGUID CHAR(32) CONSTRAINT NN01_INBOUND_FILE NOT NULL,
          FILE_NAME VARCHAR2(512) CONSTRAINT NN02_INBOUND_FILE NOT NULL,
          FILE_SIZE VARCHAR2(20) CONSTRAINT NN03_INBOUND_FILE NOT NULL,
          FILE_PATH VARCHAR2(512) CONSTRAINT NN04_INBOUND_FILE NOT NULL,
          FILE_LAST_MODIFIED_TIME TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
          PROCESSOR_ID CHAR(32) CONSTRAINT NN05_INBOUND_FILE NOT NULL,
          FS2_URI VARCHAR2(512) CONSTRAINT NN06_INBOUND_FILE NOT NULL,
          STATUS VARCHAR2(16) CONSTRAINT NN07_INBOUND_FILE NOT NULL,
          PARENT_GLOBAL_PROCESS_GUID CHAR(32),
          TRIGGER_FILE NUMBER(1) CONSTRAINT NN08_INBOUND_FILE NOT NULL,
          ORIGINATING_DC VARCHAR2(5) CONSTRAINT NN09_INBOUND_FILE NOT NULL,
          PROCESS_DC VARCHAR2(5) CONSTRAINT NN10_INBOUND_FILE NOT NULL,
          CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
          CREATED_BY VARCHAR2(128) CONSTRAINT NN11_INBOUND_FILE NOT NULL,
          MODIFIED_DATE TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
          MODIFIED_BY VARCHAR2(128)
        )
        TABLESPACE GATEWAY_TRNX
      STORAGE
      (
        PCTINCREASE 0
      )
      NOPARALLEL'
  ;

    EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM GATEWAY_APPL.INBOUND_FILE FOR GATEWAY_OWNR.INBOUND_FILE';
    EXECUTE IMMEDIATE 'GRANT SELECT ON GATEWAY_OWNR.INBOUND_FILE TO GATEWAY_APPL_ROLE';
    EXECUTE IMMEDIATE 'GRANT INSERT ON GATEWAY_OWNR.INBOUND_FILE TO GATEWAY_APPL_ROLE';
    EXECUTE IMMEDIATE 'GRANT UPDATE ON GATEWAY_OWNR.INBOUND_FILE TO GATEWAY_APPL_ROLE';

    EXECUTE IMMEDIATE 'ALTER TABLE GATEWAY_OWNR.INBOUND_FILE ADD
    CONSTRAINT PK_INBOUND_FILE PRIMARY KEY (PGUID)
    USING INDEX
      TABLESPACE GATEWAY_TRNX
      STORAGE
      (
        PCTINCREASE 0
      )';

  END IF;
END;
/