--
-- Apply quotas to users.
--

set serverout on
set echo on

ALTER USER GANESH_TEST_OWNR
    QUOTA 0 ON JUNK
    QUOTA 0 ON SYSTEM
    QUOTA 0 ON SYSAUX
    QUOTA UNLIMITED ON GANESH_TEST_CONF
;

ALTER USER GANESH_TEST_APPL
    QUOTA 0 ON JUNK
    QUOTA 0 ON SYSTEM
    QUOTA 0 ON SYSAUX
    QUOTA 0 ON GANESH_TEST_CONF
;

quit;
