
-- PROMPT Executing $Id$

-- PROMPT Generating Objects...

-----------------------------------------------------------------
-- FSM_TRANSITION_STATE
-----------------------------------------------------------------

-- PROMPT --- Creating Table FSM_TRANSITION_STATE
CREATE TABLE FSM_TRANSITION_STATE
(
	PGUID CHAR(32) NOT NULL,
	STATE_VALUE_NEW_GUID CHAR(32) NOT NULL,
	STATE_VALUE_OLD_GUID CHAR(32) NOT NULL
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

-- PROMPT --- Creating Index PK_FSM_TRANSITION_STATE (Key Constraint)

ALTER TABLE FSM_TRANSITION_STATE ADD 
	CONSTRAINT PK_FSM_TRANSITION_STATE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE JUNK
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

-- PROMPT --- Creating Index FK01_FSM_TRANSITION_STATE

CREATE INDEX FK01_FSM_TRANSITION_STATE ON FSM_TRANSITION_STATE
(
	STATE_VALUE_NEW_GUID
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-- PROMPT --- Creating Index FK02_FSM_TRANSITION_STATE

CREATE INDEX FK02_FSM_TRANSITION_STATE ON FSM_TRANSITION_STATE
(
	STATE_VALUE_OLD_GUID
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- FSM_STATE_VALUE
-----------------------------------------------------------------

-- PROMPT --- Creating Table FSM_STATE_VALUE

CREATE TABLE FSM_STATE_VALUE
(
	PGUID CHAR(32) NOT NULL,
	FSM_STATE_GUID CHAR(32) NOT NULL,
	VALUE VARCHAR2(2048) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

-- PROMPT --- Creating Index PK_FSM_STATE_VALUE (Key Constraint)

ALTER TABLE FSM_STATE_VALUE ADD 
	CONSTRAINT PK_FSM_STATE_VALUE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE JUNK
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

-- PROMPT --- Creating Index FK01_FSM_STATE_VALUE

CREATE INDEX FK01_FSM_STATE_VALUE ON FSM_STATE_VALUE
(
	FSM_STATE_GUID
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- FSM_STATE
-----------------------------------------------------------------

-- PROMPT --- Creating Table FSM_STATE

CREATE TABLE FSM_STATE
(
	PGUID CHAR(32) NOT NULL,
	EXECUTION_ID CHAR(32 BYTE) NOT NULL,
	PROCESSOR_ID CHAR(32 BYTE) NOT NULL, 
	MAILBOX_ID CHAR(32 BYTE) NOT NULL,
	PROCESSOR_NAME VARCHAR2(512) NOT NULL,
	PROCESSOR_TYPE VARCHAR2(128 BYTE) NOT NULL, 
	PROFILE_NAME VARCHAR2(128 BYTE) NOT NULL, 
	STATE_NOTES VARCHAR2(1024 BYTE) 
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

-- PROMPT --- Creating Index PK_FSM_STATE (Key Constraint)

ALTER TABLE FSM_STATE ADD 
	CONSTRAINT PK_FSM_STATE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE JUNK
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

-----------------------------------------------------------------
-- FSM_TRANSITION_LIST
-----------------------------------------------------------------

-- PROMPT --- Creating Table FSM_TRANSITION_LIST

CREATE TABLE FSM_TRANSITION_LIST
(
	PGUID CHAR(32) NOT NULL,
	EVENT_GUID CHAR(32) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

-- PROMPT --- Creating Index PK_FSM_TRANSITION_LIST (Key Constraint)

ALTER TABLE FSM_TRANSITION_LIST ADD 
	CONSTRAINT PK_FSM_TRANSITION_LIST PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE JUNK
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

-- PROMPT --- Creating Index FK01_FSM_TRANSITION_LIST

CREATE INDEX FK01_FSM_TRANSITION_LIST ON FSM_TRANSITION_LIST
(
	EVENT_GUID
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- FSM_EVENT
-----------------------------------------------------------------

-- PROMPT --- Creating Table FSM_EVENT

CREATE TABLE FSM_EVENT
(
	PGUID CHAR(32) NOT NULL,
	NAME VARCHAR2(1024) NOT NULL,
	DATA VARCHAR2(2048) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL
)
	TABLESPACE JUNK
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

-- PROMPT --- Creating Index PK_FSM_EVENT (Key Constraint)

ALTER TABLE FSM_EVENT ADD 
	CONSTRAINT PK_FSM_EVENT PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE JUNK
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;


-- PROMPT --- Adding FK Constraint FK01_FSM_TRANSITION_STATE

ALTER TABLE FSM_TRANSITION_STATE ADD 
	CONSTRAINT FK01_FSM_TRANSITION_STATE FOREIGN KEY (STATE_VALUE_NEW_GUID)
		REFERENCES FSM_STATE_VALUE (PGUID)
;

-- PROMPT --- Adding FK Constraint FK02_FSM_TRANSITION_STATE

ALTER TABLE FSM_TRANSITION_STATE ADD 
	CONSTRAINT FK02_FSM_TRANSITION_STATE FOREIGN KEY (STATE_VALUE_OLD_GUID)
		REFERENCES FSM_STATE_VALUE (PGUID)
;

-- PROMPT --- Adding FK Constraint FK01_FSM_STATE_VALUE

ALTER TABLE FSM_STATE_VALUE ADD 
	CONSTRAINT FK01_FSM_STATE_VALUE FOREIGN KEY (FSM_STATE_GUID)
		REFERENCES FSM_STATE (PGUID)
;

-- PROMPT --- Adding FK Constraint FK01_FSM_TRANSITION_LIST

ALTER TABLE FSM_TRANSITION_LIST ADD 
	CONSTRAINT FK01_FSM_TRANSITION_LIST FOREIGN KEY (EVENT_GUID)
		REFERENCES FSM_EVENT (PGUID)
;

