-----------------------------------------------------------------
-- MAILBOX
-----------------------------------------------------------------

 --- Creating Table MAILBOX

CREATE TABLE MAILBOX
(
	PGUID CHAR(32) NOT NULL,
	NAME VARCHAR2(128) NOT NULL,
	DESCRIPTION VARCHAR2(1024),
	STATUS VARCHAR2(128) NOT NULL,
	SERVICE_INST_ID NUMBER,
	SHARD_KEY VARCHAR2(512)
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
COMMENT ON COLUMN MAILBOX.PGUID IS 'primary key';
COMMENT ON COLUMN MAILBOX.NAME IS 'name of the mailbox';
COMMENT ON COLUMN MAILBOX.DESCRIPTION IS 'detailed description about the mailbox';
COMMENT ON COLUMN MAILBOX.STATUS IS 'status of the mailbox';
COMMENT ON COLUMN MAILBOX.SHARD_KEY IS 'grouping name of the mailbox';

 --- Creating Index PK_MAILBOX (Key Constraint)

ALTER TABLE MAILBOX ADD 
	CONSTRAINT PK_MAILBOX PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

-----------------------------------------------------------------
-- MAILBOX_PROPERTY
-----------------------------------------------------------------

 --- Creating Table MAILBOX_PROPERTY

CREATE TABLE MAILBOX_PROPERTY
(
	PGUID CHAR(32) NOT NULL,
	MAILBOX_GUID CHAR(32) NOT NULL,
	NAME VARCHAR2(128) NOT NULL,
	VALUE VARCHAR2(512) NOT NULL
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
COMMENT ON COLUMN MAILBOX_PROPERTY.MAILBOX_GUID IS 'primary key';

 --- Creating Index PK_MAILBOX_PROPERTY (Key Constraint)

ALTER TABLE MAILBOX_PROPERTY ADD 
	CONSTRAINT PK_MAILBOX_PROPERTY PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

 --- Creating Index FK01_MAILBOX_PROPERTY

CREATE INDEX FK01_MAILBOX_PROPERTY ON MAILBOX_PROPERTY
(
	MAILBOX_GUID
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- PROCESSOR
-----------------------------------------------------------------

 --- Creating Table PROCESSOR

CREATE TABLE PROCESSOR
(
	PGUID CHAR(32) NOT NULL,
	MAILBOX_GUID CHAR(32) NOT NULL,
	DESCRIPTION VARCHAR2(512),
	STATUS VARCHAR2(128) NOT NULL,
	TYPE VARCHAR2(128) NOT NULL,
	PROPERTIES VARCHAR2(2048),
	JAVASCRIPT_URI VARCHAR2(512),
	NAME VARCHAR2(512),
	PROTOCOL VARCHAR2(128) NOT NULL,
	EXEC_STATUS VARCHAR2(128),
	CERTIFICATE_URI VARCHAR2(512),
	SELF_SIGNED CHAR(1),
	TRUSTSTORE_ID CHAR(32)
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
COMMENT ON COLUMN PROCESSOR.MAILBOX_GUID IS 'primary key';
COMMENT ON COLUMN PROCESSOR.DESCRIPTION IS 'processor description';
COMMENT ON COLUMN PROCESSOR.TYPE IS 'discriminator column';
COMMENT ON COLUMN PROCESSOR.PROPERTIES IS 'JSON ';
COMMENT ON COLUMN PROCESSOR.JAVASCRIPT_URI IS 'refrence to filesystem, js pulled from git.';
COMMENT ON COLUMN PROCESSOR.PROTOCOL IS 'processor protocol';
COMMENT ON COLUMN PROCESSOR.EXEC_STATUS IS 'processor execution status';
COMMENT ON COLUMN PROCESSOR.CERTIFICATE_URI IS 'path which contains cerificate to upload to kms';

 --- Creating Index PK_PROCESSOR (Key Constraint)

ALTER TABLE PROCESSOR ADD 
	CONSTRAINT PK_PROCESSOR PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

 --- Creating Index FK01_PROCESSOR

CREATE INDEX FK01_PROCESSOR ON PROCESSOR
(
	MAILBOX_GUID
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- PROCESSOR_PROPERTY
-----------------------------------------------------------------

 --- Creating Table PROCESSOR_PROPERTY

CREATE TABLE PROCESSOR_PROPERTY
(
	PGUID CHAR(32) NOT NULL,
	PROCESSOR_GUID CHAR(32) NOT NULL,
	NAME VARCHAR2(128) NOT NULL,
	VALUE VARCHAR2(4000) NOT NULL
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

 --- Creating Index PK_PROCESSOR_PROPERTY (Key Constraint)

ALTER TABLE PROCESSOR_PROPERTY ADD 
	CONSTRAINT PK_PROCESSOR_PROPERTY PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

 --- Creating Index FK01_PROCESSOR_PROPERTY

CREATE INDEX FK01_PROCESSOR_PROPERTY ON PROCESSOR_PROPERTY
(
	PROCESSOR_GUID
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- CREDENTIAL
-----------------------------------------------------------------

 --- Creating Table CREDENTIAL

CREATE TABLE CREDENTIAL
(
	PGUID CHAR(32) NOT NULL,
	PROCESSOR_GUID CHAR(32) NOT NULL,
	TYPE VARCHAR2(128) NOT NULL,
	URI VARCHAR2(128),
	USERNAME VARCHAR2(128),
	PASSWORD VARCHAR2(128),
	IDP_TYPE VARCHAR2(128),
	IDP_URI VARCHAR2(128)
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
COMMENT ON COLUMN CREDENTIAL.PROCESSOR_GUID IS 'foreign key refrence to PROCESSORS';

 --- Creating Index PK_CREDENTIAL (Key Constraint)

ALTER TABLE CREDENTIAL ADD 
	CONSTRAINT PK_CREDENTIAL PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

 --- Creating Index FK01_CREDENTIAL

CREATE INDEX FK01_CREDENTIAL ON CREDENTIAL
(
	PROCESSOR_GUID
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- FOLDER
-----------------------------------------------------------------

 --- Creating Table FOLDER

CREATE TABLE FOLDER
(
	PGUID CHAR(32) NOT NULL,
	PROCESSOR_GUID CHAR(32) NOT NULL,
	DESCRIPTION VARCHAR2(250),
	TYPE VARCHAR2(50) NOT NULL,
	URI VARCHAR2(250)
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
COMMENT ON COLUMN FOLDER.PGUID IS 'primary key';
COMMENT ON COLUMN FOLDER.PROCESSOR_GUID IS 'foreign key refrence to PROCESSORS';

 --- Creating Index PK_FOLDER (Key Constraint)

ALTER TABLE FOLDER ADD 
	CONSTRAINT PK_FOLDER PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

 --- Creating Index FK01_FOLDER

CREATE INDEX FK01_FOLDER ON FOLDER
(
	PROCESSOR_GUID
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

-----------------------------------------------------------------
-- SCHED_PROFILE
-----------------------------------------------------------------

 --- Creating Table SCHED_PROFILE

CREATE TABLE SCHED_PROFILE
(
	PGUID CHAR(32) NOT NULL,
	NAME VARCHAR2(128) NOT NULL
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
COMMENT ON COLUMN SCHED_PROFILE.PGUID IS 'primary key';
COMMENT ON COLUMN SCHED_PROFILE.NAME IS 'onceinaday,onceinaweek';

 --- Creating Index PK_SCHED_PROFILE (Key Constraint)

ALTER TABLE SCHED_PROFILE ADD 
	CONSTRAINT PK_SCHED_PROFILE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

-----------------------------------------------------------------
-- SCHED_PROCESSOR
-----------------------------------------------------------------

 --- Creating Table SCHED_PROCESSOR

CREATE TABLE SCHED_PROCESSOR
(
	PGUID CHAR(32) NOT NULL,
	SCHED_PROFILE_GUID CHAR(32) NOT NULL,
	PROCESSOR_GUID CHAR(32) NOT NULL
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
COMMENT ON COLUMN SCHED_PROCESSOR.SCHED_PROFILE_GUID IS 'primary key';

 --- Creating Index PK_SCHED_PROCESSOR (Key Constraint)

ALTER TABLE SCHED_PROCESSOR ADD 
	CONSTRAINT PK_SCHED_PROCESSOR PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

 --- Creating Index FK01_SCHED_PROCESSOR

CREATE INDEX FK01_SCHED_PROCESSOR ON SCHED_PROCESSOR
(
	SCHED_PROFILE_GUID
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

 --- Creating Index FK02_SCHED_PROCESSOR

CREATE INDEX FK02_SCHED_PROCESSOR ON SCHED_PROCESSOR
(
	PROCESSOR_GUID
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

--- Adding FK Constraint FK01_CREDENTIAL

ALTER TABLE CREDENTIAL ADD 
	CONSTRAINT FK01_CREDENTIAL FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;

 --- Adding FK Constraint FK01_FOLDER

ALTER TABLE FOLDER ADD 
	CONSTRAINT FK01_FOLDER FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;

 --- Adding FK Constraint FK01_MAILBOX_PROPERTY

ALTER TABLE MAILBOX_PROPERTY ADD 
	CONSTRAINT FK01_MAILBOX_PROPERTY FOREIGN KEY (MAILBOX_GUID)
		REFERENCES MAILBOX (PGUID) ON DELETE CASCADE ENABLE
;

 --- Adding FK Constraint FK01_PROCESSOR

ALTER TABLE PROCESSOR ADD 
	CONSTRAINT FK01_PROCESSOR FOREIGN KEY (MAILBOX_GUID)
		REFERENCES MAILBOX (PGUID) ON DELETE CASCADE ENABLE
;

 --- Adding FK Constraint FK01_PROCESSOR_PROPERTY

ALTER TABLE PROCESSOR_PROPERTY ADD 
	CONSTRAINT FK01_PROCESSOR_PROPERTY FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;

 --- Adding FK Constraint FK01_SCHED_PROCESSOR

ALTER TABLE SCHED_PROCESSOR ADD 
	CONSTRAINT FK01_SCHED_PROCESSOR FOREIGN KEY (SCHED_PROFILE_GUID)
		REFERENCES SCHED_PROFILE (PGUID) ON DELETE CASCADE ENABLE
;

 --- Adding FK Constraint FK02_SCHED_PROCESSOR

ALTER TABLE SCHED_PROCESSOR ADD 
	CONSTRAINT FK02_SCHED_PROCESSOR FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;

--- Parallel Processor Execution

CREATE TABLE PARALLEL_PROCESSOR 
(
	PROCESSOR_ID CHAR(32) NOT NULL
)
	TABLESPACE MCCWAUI_DSDATA
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;
ALTER TABLE PARALLEL_PROCESSOR ADD 
	CONSTRAINT PK_PARALLEL_PROCESSOR PRIMARY KEY (PROCESSOR_ID)
		USING INDEX
			TABLESPACE MCCWAUI_DSDATA
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;