--
-- Copyright 2014 Liaison Technologies, Inc.
-- This software is the confidential and proprietary information of
-- Liaison Technologies, Inc. ("Confidential Information").  You shall
-- not disclose such Confidential Information and shall use it only in
-- accordance with the terms of the license agreement you entered into
-- with Liaison Technologies.
--

CREATE TABLE GATEWAY_OWNR.CREDENTIAL
(
	PGUID CHAR(32) CONSTRAINT NN01_CREDENTIAL NOT NULL,
	PROCESSOR_GUID CHAR(32) CONSTRAINT NN02_CREDENTIAL NOT NULL,
	TYPE VARCHAR2(128) CONSTRAINT NN03_CREDENTIAL NOT NULL,
	URI VARCHAR2(128),
	USERNAME VARCHAR2(128),
	PASSWORD VARCHAR2(128),
	IDP_TYPE VARCHAR2(128),
	IDP_URI VARCHAR2(128)
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.CREDENTIAL ADD 
	CONSTRAINT PK_CREDENTIAL PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_CREDENTIAL ON GATEWAY_OWNR.CREDENTIAL
(
	PROCESSOR_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.FOLDER
(
	PGUID CHAR(32) CONSTRAINT NN01_FOLDER NOT NULL,
	PROCESSOR_GUID CHAR(32) CONSTRAINT NN02_FOLDER NOT NULL,
	DESCRIPTION VARCHAR2(250) CONSTRAINT NN03_FOLDER NOT NULL,
	TYPE VARCHAR2(64) CONSTRAINT NN04_FOLDER NOT NULL,
	URI VARCHAR2(256)
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.FOLDER ADD 
	CONSTRAINT PK_FOLDER PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_FOLDER ON GATEWAY_OWNR.FOLDER
(
	PROCESSOR_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.FSM_EVENT
(
	PGUID CHAR(32) NOT NULL,
	NAME VARCHAR2(1024) NOT NULL,
	DATA VARCHAR2(2048) NOT NULL,
	CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.FSM_EVENT ADD 
	CONSTRAINT PK_FSM_EVENT PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE TABLE GATEWAY_OWNR.FSM_STATE
(
	PGUID CHAR(32) NOT NULL,
	EXECUTION_ID CHAR(32) NOT NULL,
	PROCESSOR_ID CHAR(32) NOT NULL,
	MAILBOX_ID CHAR(32) NOT NULL,
	PROCESSOR_NAME VARCHAR2(512) NOT NULL,
	PROCESSOR_TYPE VARCHAR2(128) NOT NULL,
	PROFILE_NAME VARCHAR2(128) NOT NULL,
	STATE_NOTES VARCHAR2(1024) NOT NULL,
	SLA_VERIFICATION_STATUS VARCHAR2(128) NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.FSM_STATE ADD 
	CONSTRAINT PK_FSM_STATE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE TABLE GATEWAY_OWNR.FSM_STATE_VALUE
(
	PGUID CHAR(32) NOT NULL,
	FSM_STATE_GUID CHAR(32) NOT NULL,
	VALUE VARCHAR2(2048) CONSTRAINT NN03_FSM_STATE_VALUE NOT NULL,
	CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN04_FSM_STATE_VALUE NOT NULL
)
	TABLESPACE GATEWAY_TRNX
	STORAGE
	(
		INITIAL 1M
		NEXT 1M
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.FSM_STATE_VALUE ADD 
	CONSTRAINT PK_FSM_STATE_VALUE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_TRNX
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_FSM_STATE_VALUE ON GATEWAY_OWNR.FSM_STATE_VALUE
(
	FSM_STATE_GUID
)
	TABLESPACE GATEWAY_TRNX
	STORAGE
	(
		INITIAL 1M
		NEXT 1M
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.FSM_TRANSITION_LIST
(
	PGUID CHAR(32) CONSTRAINT NN01_FSM_TRANSITION_LIST NOT NULL,
	EVENT_GUID CHAR(32) CONSTRAINT NN02_FSM_TRANSITION_LIST NOT NULL,
	CREATED_DATE TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP CONSTRAINT NN03_FSM_TRANSITION_LIST NOT NULL
)
	TABLESPACE GATEWAY_TRNX
	STORAGE
	(
		INITIAL 1M
		NEXT 1M
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.FSM_TRANSITION_LIST ADD 
	CONSTRAINT PK_FSM_TRANSITION_LIST PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_TRNX
			STORAGE
			(
				INITIAL 1M
				NEXT 1M
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_FSM_TRANSITION_LIST ON GATEWAY_OWNR.FSM_TRANSITION_LIST
(
	EVENT_GUID
)
	TABLESPACE GATEWAY_TRNX
	STORAGE
	(
		INITIAL 1M
		NEXT 1M
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.FSM_TRANSITION_STATE
(
	PGUID CHAR(32) CONSTRAINT NN01_FSM_TRANSITION_STATE NOT NULL,
	STATE_VALUE_NEW_GUID CHAR(32) CONSTRAINT NN02_FSM_TRANSITION_STATE NOT NULL,
	STATE_VALUE_OLD_GUID CHAR(32) CONSTRAINT NN03_FSM_TRANSITION_STATE NOT NULL
)
	TABLESPACE GATEWAY_TRNX
	STORAGE
	(
		INITIAL 1M
		NEXT 1M
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.FSM_TRANSITION_STATE ADD 
	CONSTRAINT PK_FSM_TRANSITION_STATE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_TRNX
			STORAGE
			(
				INITIAL 1M
				NEXT 1M
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_FSM_TRANSITION_STATE ON GATEWAY_OWNR.FSM_TRANSITION_STATE
(
	STATE_VALUE_NEW_GUID
)
	TABLESPACE GATEWAY_TRNX
	STORAGE
	(
		INITIAL 1M
		NEXT 1M
		PCTINCREASE 0
	)
;

CREATE INDEX FK02_FSM_TRANSITION_STATE ON GATEWAY_OWNR.FSM_TRANSITION_STATE
(
	STATE_VALUE_OLD_GUID
)
	TABLESPACE GATEWAY_TRNX
	STORAGE
	(
		INITIAL 1M
		NEXT 1M
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.MAILBOX
(
	PGUID CHAR(32) CONSTRAINT NN01_MAILBOX NOT NULL,
	NAME VARCHAR2(128) CONSTRAINT NN02_MAILBOX NOT NULL,
	DESCRIPTION VARCHAR2(1024) CONSTRAINT NN03_MAILBOX NOT NULL,
	STATUS VARCHAR2(128) CONSTRAINT NN04_MAILBOX NOT NULL,
	SHARD_KEY VARCHAR2(512),
	TENANCY_KEY CHAR(32) CONSTRAINT NN05_MAILBOX NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.MAILBOX ADD 
	CONSTRAINT PK_MAILBOX PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE TABLE GATEWAY_OWNR.MAILBOX_PROPERTY
(
	PGUID CHAR(32) CONSTRAINT NN01_MAILBOX_PROPERTY NOT NULL,
	MAILBOX_GUID CHAR(32) CONSTRAINT NN02_MAILBOX_PROPERTY NOT NULL,
	NAME VARCHAR2(128) CONSTRAINT NN03_MAILBOX_PROPERTY NOT NULL,
	VALUE VARCHAR2(512) CONSTRAINT NN04_MAILBOX_PROPERTY NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.MAILBOX_PROPERTY ADD 
	CONSTRAINT PK_MAILBOX_PROPERTY PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_MAILBOX_PROPERTY ON GATEWAY_OWNR.MAILBOX_PROPERTY
(
	MAILBOX_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.MAILBOX_SVC_INSTANCE
(
	PGUID CHAR(32) CONSTRAINT NN01_MAILBOX_SVC_INSTANCE NOT NULL,
	SERVICE_INSTANCE_GUID CHAR(32) CONSTRAINT NN02_MAILBOX_SVC_INSTANCE NOT NULL,
	MAILBOX_GUID CHAR(32) CONSTRAINT NN03_MAILBOX_SVC_INSTANCE NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.MAILBOX_SVC_INSTANCE ADD 
	CONSTRAINT PK_MAILBOX_SVC_INSTANCE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_MAILBOX_SVC_INSTANCE ON GATEWAY_OWNR.MAILBOX_SVC_INSTANCE
(
	SERVICE_INSTANCE_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE INDEX FK02_MAILBOX_SVC_INSTANCE ON GATEWAY_OWNR.MAILBOX_SVC_INSTANCE
(
	MAILBOX_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.PROCESSOR
(
	PGUID CHAR(32) CONSTRAINT NN01_PROCESSOR NOT NULL,
	MAILBOX_GUID CHAR(32) CONSTRAINT NN02_PROCESSOR NOT NULL,
	SERVICE_INSTANCE_GUID CHAR(32) CONSTRAINT NN03_PROCESSOR NOT NULL,
	DESCRIPTION VARCHAR2(512) CONSTRAINT NN04_PROCESSOR NOT NULL,
	STATUS VARCHAR2(128) CONSTRAINT NN05_PROCESSOR NOT NULL,
	TYPE VARCHAR2(128) CONSTRAINT NN06_PROCESSOR NOT NULL,
	PROPERTIES VARCHAR2(2048),
	JAVASCRIPT_URI VARCHAR2(512),
	NAME VARCHAR2(512),
	PROTOCOL VARCHAR2(128) CONSTRAINT NN07_PROCESSOR NOT NULL,
	EXEC_STATUS VARCHAR2(128),
	CERTIFICATE_URI VARCHAR2(20),
	SELF_SIGNED NUMBER(1) CONSTRAINT NN08_PROCESSOR NOT NULL,
	TRUSTSTORE_ID CHAR(32)
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.PROCESSOR ADD 
	CONSTRAINT PK_PROCESSOR PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_PROCESSOR ON GATEWAY_OWNR.PROCESSOR
(
	MAILBOX_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE INDEX FK02_PROCESSOR ON GATEWAY_OWNR.PROCESSOR
(
	SERVICE_INSTANCE_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.PROCESSOR_PROPERTY
(
	PGUID CHAR(32) CONSTRAINT NN01_PROCESSOR_PROPERTY NOT NULL,
	PROCESSOR_GUID CHAR(32) CONSTRAINT NN02_PROCESSOR_PROPERTY NOT NULL,
	NAME VARCHAR2(128) CONSTRAINT NN03_PROCESSOR_PROPERTY NOT NULL,
	VALUE VARCHAR2(512) CONSTRAINT NN04_PROCESSOR_PROPERTY NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.PROCESSOR_PROPERTY ADD 
	CONSTRAINT PK_PROCESSOR_PROPERTY PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_PROCESSOR_PROPERTY ON GATEWAY_OWNR.PROCESSOR_PROPERTY
(
	PROCESSOR_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.SCHED_PROCESSOR
(
	PGUID CHAR(32) CONSTRAINT NN01_SCHED_PROCESSOR NOT NULL,
	SCHED_PROFILE_GUID CHAR(32) CONSTRAINT NN02_SCHED_PROCESSOR NOT NULL,
	PROCESSOR_GUID CHAR(32) CONSTRAINT NN03_SCHED_PROCESSOR NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.SCHED_PROCESSOR ADD 
	CONSTRAINT PK_SCHED_PROCESSOR PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE INDEX FK01_SCHED_PROCESSOR ON GATEWAY_OWNR.SCHED_PROCESSOR
(
	SCHED_PROFILE_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE INDEX FK02_SCHED_PROCESSOR ON GATEWAY_OWNR.SCHED_PROCESSOR
(
	PROCESSOR_GUID
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
;

CREATE TABLE GATEWAY_OWNR.SCHED_PROFILE
(
	PGUID CHAR(32) CONSTRAINT NN01_SCHED_PROFILE NOT NULL,
	NAME VARCHAR2(128) CONSTRAINT NN02_SCHED_PROFILE NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.SCHED_PROFILE ADD 
	CONSTRAINT PK_SCHED_PROFILE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

CREATE TABLE GATEWAY_OWNR.SERVICE_INSTANCE
(
	PGUID CHAR(32) CONSTRAINT NN01_SERVICE_INSTANCE NOT NULL,
	SERVICE_INSTANCE_ID VARCHAR2(32) CONSTRAINT NN02_SERVICE_INSTANCE NOT NULL
)
	TABLESPACE GATEWAY_CONF
	STORAGE
	(
		INITIAL 64K
		NEXT 64K
		PCTINCREASE 0
	)
	NOPARALLEL
;

ALTER TABLE GATEWAY_OWNR.SERVICE_INSTANCE ADD 
	CONSTRAINT PK_SERVICE_INSTANCE PRIMARY KEY (PGUID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

ALTER TABLE GATEWAY_OWNR.SERVICE_INSTANCE ADD 
	CONSTRAINT AK01_SERVICE_INSTANCE UNIQUE (SERVICE_INSTANCE_ID)
		USING INDEX
			TABLESPACE GATEWAY_CONF
			STORAGE
			(
				INITIAL 64K
				NEXT 64K
				PCTINCREASE 0
			)
;

ALTER TABLE GATEWAY_OWNR.CREDENTIAL ADD 
	CONSTRAINT FK01_CREDENTIAL FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES GATEWAY_OWNR.PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;

ALTER TABLE GATEWAY_OWNR.FOLDER ADD 
	CONSTRAINT FK01_FOLDER FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES GATEWAY_OWNR.PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;

ALTER TABLE GATEWAY_OWNR.FSM_STATE_VALUE ADD 
	CONSTRAINT FK01_FSM_STATE_VALUE FOREIGN KEY (FSM_STATE_GUID)
		REFERENCES GATEWAY_OWNR.FSM_STATE (PGUID)
;

ALTER TABLE GATEWAY_OWNR.FSM_TRANSITION_LIST ADD 
	CONSTRAINT FK01_FSM_TRANSITION_LIST FOREIGN KEY (EVENT_GUID)
		REFERENCES GATEWAY_OWNR.FSM_EVENT (PGUID)
;

ALTER TABLE GATEWAY_OWNR.FSM_TRANSITION_STATE ADD 
	CONSTRAINT FK01_FSM_TRANSITION_STATE FOREIGN KEY (STATE_VALUE_NEW_GUID)
		REFERENCES GATEWAY_OWNR.FSM_STATE_VALUE (PGUID)
;

ALTER TABLE GATEWAY_OWNR.FSM_TRANSITION_STATE ADD 
	CONSTRAINT FK02_FSM_TRANSITION_STATE FOREIGN KEY (STATE_VALUE_OLD_GUID)
		REFERENCES GATEWAY_OWNR.FSM_STATE_VALUE (PGUID)
;

ALTER TABLE GATEWAY_OWNR.MAILBOX_PROPERTY ADD 
	CONSTRAINT FK01_MAILBOX_PROPERTY FOREIGN KEY (MAILBOX_GUID)
		REFERENCES GATEWAY_OWNR.MAILBOX (PGUID) ON DELETE CASCADE ENABLE
;

ALTER TABLE GATEWAY_OWNR.MAILBOX_SVC_INSTANCE ADD 
	CONSTRAINT FK01_MAILBOX_SVC_INSTANCE FOREIGN KEY (SERVICE_INSTANCE_GUID)
		REFERENCES GATEWAY_OWNR.SERVICE_INSTANCE (PGUID)
;

ALTER TABLE GATEWAY_OWNR.MAILBOX_SVC_INSTANCE ADD 
	CONSTRAINT FK02_MAILBOX_SVC_INSTANCE FOREIGN KEY (MAILBOX_GUID)
		REFERENCES GATEWAY_OWNR.MAILBOX (PGUID)
;

ALTER TABLE GATEWAY_OWNR.PROCESSOR ADD 
	CONSTRAINT FK01_PROCESSOR FOREIGN KEY (MAILBOX_GUID)
		REFERENCES GATEWAY_OWNR.MAILBOX (PGUID) ON DELETE CASCADE ENABLE
;

ALTER TABLE GATEWAY_OWNR.PROCESSOR ADD 
	CONSTRAINT FK02_PROCESSOR FOREIGN KEY (SERVICE_INSTANCE_GUID)
		REFERENCES GATEWAY_OWNR.SERVICE_INSTANCE (PGUID)
;

ALTER TABLE GATEWAY_OWNR.PROCESSOR_PROPERTY ADD 
	CONSTRAINT FK01_PROCESSOR_PROPERTY FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES GATEWAY_OWNR.PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;

ALTER TABLE GATEWAY_OWNR.SCHED_PROCESSOR ADD 
	CONSTRAINT FK01_SCHED_PROCESSOR FOREIGN KEY (SCHED_PROFILE_GUID)
		REFERENCES GATEWAY_OWNR.SCHED_PROFILE (PGUID) ON DELETE CASCADE ENABLE
;

ALTER TABLE GATEWAY_OWNR.SCHED_PROCESSOR ADD 
	CONSTRAINT FK02_SCHED_PROCESSOR FOREIGN KEY (PROCESSOR_GUID)
		REFERENCES GATEWAY_OWNR.PROCESSOR (PGUID) ON DELETE CASCADE ENABLE
;
