CREATE OR REPLACE SYNONYM GATEWAY_APPL.CREDENTIAL
	FOR GATEWAY_OWNR.CREDENTIAL
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FOLDER
	FOR GATEWAY_OWNR.FOLDER
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_EVENT
	FOR GATEWAY_OWNR.FSM_EVENT
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_STATE
	FOR GATEWAY_OWNR.FSM_STATE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_STATE_VALUE
	FOR GATEWAY_OWNR.FSM_STATE_VALUE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_TRANSITION_LIST
	FOR GATEWAY_OWNR.FSM_TRANSITION_LIST
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FSM_TRANSITION_STATE
	FOR GATEWAY_OWNR.FSM_TRANSITION_STATE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.MAILBOX
	FOR GATEWAY_OWNR.MAILBOX
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.MAILBOX_PROPERTY
	FOR GATEWAY_OWNR.MAILBOX_PROPERTY
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.MAILBOX_SVC_INSTANCE
	FOR GATEWAY_OWNR.MAILBOX_SVC_INSTANCE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.PROCESSOR
	FOR GATEWAY_OWNR.PROCESSOR
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.PROCESSOR_PROPERTY
	FOR GATEWAY_OWNR.PROCESSOR_PROPERTY
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.PROCESSOR_SEMAPHORE
	FOR GATEWAY_OWNR.PROCESSOR_SEMAPHORE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.SCHED_PROCESSOR
	FOR GATEWAY_OWNR.SCHED_PROCESSOR
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.SCHED_PROFILE
	FOR GATEWAY_OWNR.SCHED_PROFILE
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.SERVICE_INSTANCE
	FOR GATEWAY_OWNR.SERVICE_INSTANCE
;

