CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.CREDENTIAL
	FOR GANESH_TEST_OWNR.CREDENTIAL
;

CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.FOLDER
	FOR GANESH_TEST_OWNR.FOLDER
;

CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.MAILBOX
	FOR GANESH_TEST_OWNR.MAILBOX
;

CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.MAILBOX_PROPERTY
	FOR GANESH_TEST_OWNR.MAILBOX_PROPERTY
;

CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.PROCESSOR
	FOR GANESH_TEST_OWNR.PROCESSOR
;

CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.PROCESSOR_PROPERTY
	FOR GANESH_TEST_OWNR.PROCESSOR_PROPERTY
;

CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.SCHED_PROCESSOR
	FOR GANESH_TEST_OWNR.SCHED_PROCESSOR
;

CREATE OR REPLACE SYNONYM GANESH_TEST_APPL.SCHED_PROFILE
	FOR GANESH_TEST_OWNR.SCHED_PROFILE
;

