--
-- Recreate service-related object roles
--

DECLARE
  v_stmt    VARCHAR2(4000);

FUNCTION RoleGranted(
  p_role IN USER_ROLE_PRIVS.Granted_Role%Type
) RETURN BOOLEAN
IS
  v_role  USER_ROLE_PRIVS.Granted_Role%Type;
BEGIN
  SELECT Granted_Role
    INTO v_role
    FROM USER_ROLE_PRIVS
    WHERE Granted_Role = p_role;
  RETURN TRUE;
EXCEPTION
  WHEN NO_DATA_FOUND
  THEN
    RETURN FALSE;
END RoleGranted;

PROCEDURE ResetRole(
  p_role IN USER_ROLE_PRIVS.Granted_Role%Type
)
IS
BEGIN
  FOR c in (
  SELECT
      UNIQUE table_name, grantee
    FROM
      USER_TAB_PRIVS
    WHERE
      grantee = p_role
  )
  LOOP
    EXECUTE IMMEDIATE 'REVOKE ALL ON ' || c.table_name || ' FROM ' || c.grantee;
  END LOOP;
END ResetRole;

BEGIN

  IF RoleGranted('GANESH_TEST_APPL_ROLE') THEN
    ResetRole('GANESH_TEST_APPL_ROLE');
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.CREDENTIAL TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.CREDENTIAL TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.CREDENTIAL TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.FOLDER TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.FOLDER TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.FOLDER TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.MAILBOX_PROPERTY TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.MAILBOX_PROPERTY TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.MAILBOX_PROPERTY TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.MAILBOX TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.MAILBOX TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.MAILBOX TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.PROCESSOR_PROPERTY TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.PROCESSOR_PROPERTY TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.PROCESSOR_PROPERTY TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.PROCESSOR TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.PROCESSOR TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.PROCESSOR TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.SCHED_PROCESSOR TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.SCHED_PROCESSOR TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.SCHED_PROCESSOR TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT SELECT ON GANESH_TEST_OWNR.SCHED_PROFILE TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT INSERT ON GANESH_TEST_OWNR.SCHED_PROFILE TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
    v_stmt := 'GRANT UPDATE ON GANESH_TEST_OWNR.SCHED_PROFILE TO GANESH_TEST_APPL_ROLE';
    EXECUTE IMMEDIATE v_stmt;
  END IF;

  IF RoleGranted('GANESH_TEST_OWNR_ROLE') THEN
    ResetRole('GANESH_TEST_OWNR_ROLE');
  END IF;

END;
/
