--
-- Apply quotas to users.
--

set serverout on
set echo on

ALTER USER GATEWAY_OWNR
    QUOTA 0 ON JUNK
    QUOTA 0 ON SYSTEM
    QUOTA 0 ON SYSAUX
    QUOTA UNLIMITED ON GATEWAY_CONF
    QUOTA UNLIMITED ON GATEWAY_TRNX
;

ALTER USER GATEWAY_APPL
    QUOTA 0 ON JUNK
    QUOTA 0 ON SYSTEM
    QUOTA 0 ON SYSAUX
    QUOTA 0 ON GATEWAY_CONF
    QUOTA 0 ON GATEWAY_TRNX
;

quit;
