
PROMPT Executing $Id$

PROMPT Generating Objects...

CREATE OR REPLACE SYNONYM GATEWAY_APPL.CREDENTIAL
	FOR GATEWAY_OWNR.CREDENTIAL
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.FOLDER
	FOR GATEWAY_OWNR.FOLDER
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.MAILBOX
	FOR GATEWAY_OWNR.MAILBOX
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.MAILBOX_PROPERTY
	FOR GATEWAY_OWNR.MAILBOX_PROPERTY
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.PROCESSOR
	FOR GATEWAY_OWNR.PROCESSOR
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.PROCESSOR_PROPERTY
	FOR GATEWAY_OWNR.PROCESSOR_PROPERTY
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.SCHED_PROCESSOR
	FOR GATEWAY_OWNR.SCHED_PROCESSOR
;

CREATE OR REPLACE SYNONYM GATEWAY_APPL.SCHED_PROFILE
	FOR GATEWAY_OWNR.SCHED_PROFILE
;

PROMPT Object Generation Complete
