
-- executed as SYS/SYSTEM:

set serverout on
set echo on

-- drop tables

DROP TABLE CREDENTIAL;
DROP TABLE FOLDER;
DROP TABLE MAILBOX_PROPERTY;
DROP TABLE PROCESSOR_PROPERTY;
DROP TABLE SCHED_PROCESSOR;
DROP TABLE SCHED_PROFILE;
DROP TABLE PROCESSOR;
DROP TABLE MAILBOX;