
-- executed as SYS/SYSTEM:

set serverout on
set echo on

-- drop users

DROP USER GATEWAY_OWNR CASCADE;
DROP USER GATEWAY_APPL CASCADE;

-- drop profiles

DROP PROFILE GATEWAY_OWNR_PROFILE CASCADE;
DROP PROFILE GATEWAY_APPL_PROFILE CASCADE;

-- drop roles

DROP ROLE GATEWAY_OWNR_ROLE;
DROP ROLE GATEWAY_APPL_ROLE;

-- drop tablespaces

DROP TABLESPACE GATEWAY_CONF INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE GATEWAY_TEMP_01 INCLUDING CONTENTS AND DATAFILES;
