

CREATE PROFILE GATEWAY_OWNR_PROFILE LIMIT
	IDLE_TIME 60
	PASSWORD_LIFE_TIME UNLIMITED
;

CREATE PROFILE GATEWAY_APPL_PROFILE LIMIT
	CONNECT_TIME UNLIMITED
	PASSWORD_LIFE_TIME UNLIMITED
;

ALTER USER GATEWAY_OWNR
	PROFILE GATEWAY_OWNR_PROFILE
	QUOTA 0 ON JUNK
	QUOTA 0 ON SYSTEM
	QUOTA 0 ON SYSAUX
	QUOTA UNLIMITED ON GATEWAY_CONF
;

ALTER USER GATEWAY_APPL
	PROFILE GATEWAY_APPL_PROFILE
	QUOTA 0 ON JUNK
	QUOTA 0 ON SYSTEM
	QUOTA 0 ON SYSAUX
	QUOTA 0 ON GATEWAY_CONF
;

